export declare const CWD: string;
export declare const SRC_DIR: string;
export declare const TS_CONFIG: string;
export declare const POSTCSS_CONFIG: string;
export declare const CAST_CONFIG: string;
export declare const TEMPLATES_DIR: string;
export declare const CLI_PACKAGE_JSON: string;
export declare const WEBPACK_RESOLVE_EXTENSIONS: string[];
export declare const PRIMARY_COLOR = "#3a7afe";
export declare const SITE_MOBILE_MAIN: string;
export declare const SITE_MOBILE_HTML: string;
export declare const SITE_PC_MAIN: string;
export declare const SITE_PC_HTML: string;
export declare const SITE_DIR: string;
export declare const SITE_CONFIG: string;
export declare const SITE_PC_ROUTES: string;
export declare const SITE_MOBILE_ROUTES: string;
